### ISSUE TITLE
Is this supported to Fire TV devices

### ISSUE THREAD

**Issue by satyamub** [eXaLy/DIALTestFireTV#1]
Have you tried uploading this to amazon store. does it get supported by fire tv device list? if yes, what are the things you included in manifest to do so?

**Comment by eXaLy** [comment]
Hi @satyamub 
If you submit an app to Amazon App Store, you can choose the targeted devices. 
The Amazon team will test your app if it works on the selected devices you want to target.

Additional information:
https://developer.amazon.com/public/support/submitting-your-app/tech-docs/getting-started-with-device-targeting

Amazon apps (for Kindle Fire, Fire TV etc.) are basically just Android apps.

My DIALTestFireTV project is just a simple demo of implementing the DIAL feature for a FireTV Android app.
Based on the following documentation: https://developer.amazon.com/public/solutions/devices/fire-tv/docs/dial-integration

If you're interested, as Cordova developer, I have also created a plugin to support the DIAL based on the mentioned documentation: https://github.com/vigour-io/cordova-plugin-firetv-dial
